config/routes.rb
# -*- encoding : utf-8 -*-
AixInventory::Application.routes.draw do

  resources :reports

  match "/reports/report_search/:id" => "reports#show", as: "search_report", :via => [:post]
  match "/reports/:id/server_link/:name" => "reports#server_link", as: "server_link_report", :via => [:get]
  match "/reports/report_search/:id/server_link/:name" => "reports#server_link", as: "server_link_report", :via => [:get]
  match "/servers/:id/load_tab/:tab"  => "servers#load_tab", as: "load_tab_server", :via => [:get]

  resources :import_reports

  resources :activities

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  resources :users

  resources :servers, :only => [:show, :edit]

  resources :uploads do
    member do
      get :import
      get :view_logs
    end
  end

  resources :statistics, :only => [:index]
  match "/statistics/reander_stats/:stats" => "statistics#render_stats", as: "render_stats", :via => [:get]

  get :contacts, to: "contacts#index"

  root to: 'reports#index'

end

app/models/upload.rb
# == Schema Information
#
# Table name: uploads
#
#  id                  :integer          not null, primary key
#  upload_file_name    :string(255)
#  upload_content_type :string(255)
#  upload_file_size    :integer
#  upload_updated_at   :string(255)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  import_type         :string(255)
#  workflow_state      :string(255)
#

class Upload < ActiveRecord::Base
  attr_accessible :upload, :import_type
  has_attached_file :upload, :path => ":rails_root/import/new/:import_type/:filename"

  TYPES = %w[server san]
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  load_and_authorize_resource
  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all

    respond_to do |format|
      format.html # index.html.haml
    end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @upload }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
  end

  # GET/uploads/import/1
  def import
    @upload = Upload.find(params[:id])
    redirect_to :uploads
  end

  # POST /uploads
  # POST /uploads.json
  def create
    # TO DO: make it cleaner
    if params[:commit] == "Delete"
       Upload.destroy_all( {id: params[:upload_ids] } )
      redirect_to uploads_url, :notice => "uploaded files deleted"
      return
    end
    respond_to do |format|
      format.html { redirect_to uploads_url, alert: "Nothing to upload" }
      format.js  {@upload = Upload.create(params[:upload])}
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.json
  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  def view_logs
    @upload = Upload.find(params[:id])
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    unless params[:upload_ids].nil? or params[:upload_ids].empty?
      Upload.destroy_all( {id: params[:upload_ids] } )
      redirect_to uploads_url, :notice => "uploaded files deleted"
    end

    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_import_logs.html.haml
- if @upload.import_log.nil?
  %b no log to display
- else
  %b number of lines imported successfully :
  = @upload.import_log.success_count
  %br
  %b number of lines with errors  :
  = @upload.import_log.error_count
  %br
  %b job started at : 
  = @upload.import_log.created_at.strftime('%Y/%m/%d %H:%M')
  %br
  %b job duration : 
  = (@upload.import_log.updated_at - @upload.import_log.created_at).to_i 
  seconds
  %h1 errors
  = simple_format @upload.import_log.content

app/views/uploads/_modal_window.html.haml
#modal-window.modal.hide
  .modal-header
    %a.close{"data-dismiss" => "modal"} ×
    %h3 import log
  .modal-body
    %p no data
  .modal-footer
    

    
  

app/views/uploads/_upload.html.haml
%tr
  %td= link_to upload.upload_file_name, upload.upload.url(:original)
  %td= upload.import_type
  %td
  %td
    = link_to "import", import_upload_path(upload), :class => 'btn btn-mini btn-warning'
    = link_to "delete", upload_path(upload), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

  %td= check_box_tag "upload_ids[]", upload.id

app/views/uploads/_upload_tmpl.html.erb
<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>file name</th>
        <th>choose import type :</th>
        <th>Action</th>
      </tr>
    </thead>    
    <tbody>
      <tr>
        <td>{%=o.name%}</td>
        <td><%= select("upload", "import_type", Upload::TYPES) %></td>
        <td><%= link_to "upload", '#', :class => "btn btn-primary upload" %></td>
      </tr>
      <tr>
        <td colspan=3>
          <b>upload status</b>
          <div class="progress progress-success progress-striped active"><div class="bar" style="width: 0%;"></div></div>
        </td>
      </tr>
    </tbody>
  </table>
</div>
</script>

app/views/uploads/create.js.erb
<% if @upload.new_record? %>
  alert("Failed to upload file: <%= @upload.errors.full_messages.join(', ').html_safe %> ");
<% else %>
  $('#files').append("<%= j render(@upload) %>");
<% end %>

app/views/uploads/index.html.haml
%br

.row.fileupload-buttonbar
  .span7.offset3
    = form_for Upload.new, :html => { :multipart => true, :id => "fileupload"  } do |f|
      %span.btn.btn-success.fileinput-button
        %i.icon-plus.icon-white
        %span Add files...
        = f.file_field :upload      
      =f.submit "Delete", :class => "btn btn-danger"        
      %table.table.table-bordered.table-striped#files
        %thead
          %th file
          %th import_type
          %th status
          %th action
          %th select
        %tbody
          - @uploads.each do |upload|
            = render(upload)
      =render 'upload_tmpl'
=render 'modal_window'

app/views/uploads/view_logs.js.erb
$('.modal-body').html("<%= escape_javascript(render :partial => 'import_logs', :object => @upload) %>");