config/routes.rb
# -*- encoding : utf-8 -*-
AixInventory::Application.routes.draw do

  resources :reports

  match "/reports/report_search/:id" => "reports#show", as: "search_report", :via => [:post]
  match "/reports/:id/server_link/:name" => "reports#server_link", as: "server_link_report", :via => [:get]
  match "/reports/report_search/:id/server_link/:name" => "reports#server_link", as: "server_link_report", :via => [:get]
  match "/servers/:id/load_tab/:tab"  => "servers#load_tab", as: "load_tab_server", :via => [:get]

  resources :import_reports

  resources :activities

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  resources :users

  resources :servers, :only => [:show, :edit]

  resources :uploads do
    member do
      get :import
      get :view_logs
    end
  end

  resources :statistics, :only => [:index]
  match "/statistics/reander_stats/:stats" => "statistics#render_stats", as: "render_stats", :via => [:get]

  get :contacts, to: "contacts#index"

  root to: 'reports#index'

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :string(255)
#  report_type :string(255)
#  user_id     :integer
#

class Report < ActiveRecord::Base
  attr_accessible :name, :description, :report_type, :os_type, :report_fields_attributes, :selected_fields, :operating_system_type_ids, :customer_ids
  has_many :report_fields
  accepts_nested_attributes_for :report_fields
  has_many :report_operating_system_types
  has_many :operating_system_types, :through => :report_operating_system_types
  has_many :report_customers
  has_many :customers, :through => :report_customers
  belongs_to :user
  validates_presence_of :name, :report_type

  TYPES = %w[server san]
  FIELD_TYPES = %w[server_attribute server san_infra hardware lparstat linux_port aix_port]

  def selected_fields
    report_fields
  end

  def selected_fields=(fields)
    report_ids=[]
    fields.split(',').each do |value|
      match_results=value.match(/(\S+)\[(\S+)\]/)
      next if match_results.nil?
      field_type=match_results[1]
      attribute=match_results[2]
      next unless FIELD_TYPES.include? field_type
      puts "toto"
      report=report_fields.find_or_initialize_by_select_attribute(association_type: field_type, select_attribute: attribute)
      puts report.inspect
      report_ids << report.id

    end
    #delete ids
    clean_ids=report_field_ids - report_ids
    ReportField.find_all_by_id(clean_ids).each do |field|
      field.destroy
    end

    report_fields
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  load_and_authorize_resource
  def index
    @reports=Report.where(user_id: current_user.id )
  end

  def show
    if params[:clear].present?
      params[:q] = nil
      params[:sSearch]=nil
      session[:last_query] = nil
    end

    if params[:q].present?
      session[:last_query] = params[:q]
    elsif session[:last_query].present?
      params.merge( session[:last_query] )
    end

    report = Report.find(params[:id])

    @report_builder=ReportBuilder.build(report, session[:last_query])
    @search = @report_builder.search
    @columns= @report_builder.columns

    @report_builder.build_search_condition

    respond_to do |format|
      format.html
      format.json {
        @secho = params[:sEcho].to_i
        @data = @report_builder.datatable_data(page, per_page)
        @total_records = @report_builder.total_records
        @total_display_records = @report_builder.total_display_records
      }
      format.xlsx {
        @first_header = @report_builder.first_header
        @data = @report_builder.xlsx_data
      }
    end
  end

  def new

    render status: 403 unless Report::TYPES.include? params[:report_type]
    @report=Report.new(report_type: params[:report_type])


    respond_to do |format|
      format.html
    end
  end

  def create
    @report = Report.new(params[:report])
    @report.user_id = current_user.id

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @firmware = Report.find(params[:id])
  end

  def server_link
    server=Server.find_by_hostname(params[:name])
    redirect_to server_path(server)
  end

  # PUT /report/1
  # PUT /report/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_condition_fields.html.haml
.field
  = f.attribute_fields do |a|
    = a.attribute_select associations: [:health_checks, :server_attributes, :customer]
  = f.predicate_select only: [:cont, :not_cont, :eq, :not_eq], compounds: false
  = f.value_fields do |v|
    = v.text_field :value
  = link_to "remove", '#', class: "remove_fields btn btn-danger"

app/views/reports/_form_header.html.haml
.row-fluid
  .span12
    %div#form_report
      .page-header
        %h1
          = f.input :name, label: false do
            = f.input_field :name, placeholder: "Name"
            = f.input_field :description, placeholder: "Description"
            = f.submit
          = f.hidden_field :selected_fields

app/views/reports/_linux_port_columns.html.haml
%h2 linux ports
- for column in LinuxPort.column_names - ['id', "wwpn_id", "created_at", "updated_at" ]
  %il{ id: "linux_port[#{column}]", style: "cursor:move", class: "draggable label"}= column

app/views/reports/_lparstat_columns.html.haml
%h2 lparstats
- for column in Lparstat.column_names - ['id', "created_at", "updated_at", "server_id" ]
  %il{ id: "lparstat[#{column}]", style: "cursor:move", class: "draggable label"}= column

app/views/reports/_report_field_fields.html.haml
%fieldset
  = f.label :content, "Server Field"
  = f.collection_select :select_attribute, ServerAttribute.group(:name), :name, :name
  = link_to "remove", '#', class: "remove_fields btn btn-danger"

app/views/reports/_report_scope.html.haml
%h1 Select report scope
.row-fluid
  .span4
    %h2.ui-widget-header os type
    .ui-widget-content
      %ul
        - OperatingSystemType.all.each do |os_type|
          %li
            = check_box_tag "report[operating_system_type_ids][]", os_type.id, report.operating_system_type_ids.include?(os_type.id)
            = os_type.name
  .span8
    %h2.ui-widget-header customers
    #customers.ui-widget-content
      #check_all.btn Check / Uncheck All
      %ul.inline
        - Customer.order("name ASC").all.each do |customer|
          %li
            = check_box_tag "report[customer_ids][]", customer.id, report.customer_ids.include?(customer.id)
            = customer.name

app/views/reports/_san_condition_fields.html.haml
.field
  = f.attribute_fields do |a|
    = a.attribute_select associations: [:server, :san_infra, :server_attributes, :customer]
  = f.predicate_select only: [:cont, :not_cont, :eq, :not_eq], compounds: false
  = f.value_fields do |v|
    = v.text_field :value
  = link_to "remove", '#', class: "remove_fields btn btn-danger"

app/views/reports/_san_form.html.haml
= simple_form_for @report do |f|
  = hidden_field_tag "report[report_type]", 'san'
  = render partial: 'form_header', locals: {f: f}

  = render partial: 'report_scope', locals: { report: @report}

  %h1 Fields in report
  .row-fluid
    .span4
      = render partial: 'report_fields', locals: {report: @report}
    .span8
      %h2.ui-widget-header
        available fields
      .ui-widget-content
        %ul
          = render partial: 'server_columns'
          = render partial: 'server_attribute_columns'
          = render partial: 'san_infra_columns'
          = render partial: 'linux_port_columns'
= link_to "back", reports_path, class: "btn btn-warning"

app/views/reports/_server_columns.html.haml
%h2 server
- for column in Server.column_names - ['id', "created_at", "hardware_id", "operating_system_id", "operating_system_type_id", "customer_id", "updated_at" ] + ['os_type', 'os_version', 'customer_name']
  %il{ id: "server[#{column}]", style: "cursor:move", class: "draggable label"}= column

app/views/reports/_server_condition_fields.html.haml
.field
  = f.attribute_fields do |a|
    = a.attribute_select associations: [:server_attributes, :customer, :operating_system, :operating_system_type]
  = f.predicate_select only: [:cont, :not_cont, :eq, :not_eq], compounds: false
  = f.value_fields do |v|
    = v.text_field :value
  = link_to "remove", '#', class: "remove_fields btn btn-danger"

app/views/reports/_server_form.html.haml
= simple_form_for @report do |f|
  = hidden_field_tag "report[report_type]", 'server'
  = render partial: 'form_header', locals: {f: f}

  = render partial: 'report_scope', locals: { report: @report}
  %h1 Fields in report
  .row-fluid
    .span4
      = render partial: 'report_fields', locals: {report: @report}
    .span8
      %h2.ui-widget-header
        available fields
      .ui-widget-content
        %ul
          = render partial: 'server_columns'
          = render partial: 'server_attribute_columns'
          = render partial: 'hardware_columns'
          = render partial: 'lparstat_columns'
= link_to "back", reports_path, class: "btn btn-warning"

app/views/reports/edit.html.haml
= render partial: "#{@report.report_type}_form"

app/views/reports/new.html.haml
= render partial: "#{@report.report_type}_form"

app/views/reports/show.html.haml
.row-fluid
  .span12
    %h1
      = @report.name
      %div{:id => "#{@report.report_type}_report"}
      #search_toggle.btn.btn-primary
        search
      #action_toggle.btn.btn-primary
        actions
    #action_menu
      %h2 Actions
      = link_to t('.edit', :default => t("helpers.links.edit")), edit_report_path(@report), :class => 'btn'
      = link_to "back", reports_path, class: "btn btn-danger"
      = link_to "Excel Export", report_path(@report, :format => :xlsx), :class => "btn btn-warning"
    #search_menu
      %h2 Advanced search
      = search_form_for @search, :url=> search_report_path(@report), method: :post do |f|
        = f.condition_fields do |c|
          = render @report.report_type + "_condition_fields", f: c
        = link_to_add_fields "Add Conditions", f, :condition, "#{@report.report_type}_condition"
        .form-actions
          =f.submit "Search", :class => "btn btn-success"
          = link_to "Reset", report_path(@report, {:clear => 'yes'}), :class => "btn btn-primary"
    %table{ :id => "report_datatable", :class => "table table-striped", :data => { :source => "#{ report_url(format: "json") }" } }
      %thead
        %tr
          %th server
          - @columns.each do |column|
            %th=column
      %tbody
  .span3