config/routes.rb
# -*- encoding : utf-8 -*-
AixInventory::Application.routes.draw do

  resources :reports

  match "/reports/report_search/:id" => "reports#show", as: "search_report", :via => [:post]
  match "/reports/:id/server_link/:name" => "reports#server_link", as: "server_link_report", :via => [:get]
  match "/reports/report_search/:id/server_link/:name" => "reports#server_link", as: "server_link_report", :via => [:get]
  match "/servers/:id/load_tab/:tab"  => "servers#load_tab", as: "load_tab_server", :via => [:get]

  resources :import_reports

  resources :activities

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  resources :users

  resources :servers, :only => [:show, :edit]

  resources :uploads do
    member do
      get :import
      get :view_logs
    end
  end

  resources :statistics, :only => [:index]
  match "/statistics/reander_stats/:stats" => "statistics#render_stats", as: "render_stats", :via => [:get]

  get :contacts, to: "contacts#index"

  root to: 'reports#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UNIX inventory</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>


<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href= <%= reports_path %> >UNIX Inventory</a>

      <div class="nav-collapse">
        <ul class="nav">
          <% if user_signed_in?  %>
            <li class="<%= 'active' if current_page?(reports_path) %>"><%= link_to "Reports", reports_path %></li>
           <li class="<%= 'active' if current_page?(statistics_path) %>"><%= link_to "Statistics", statistics_path %></li>
            <% if current_user.role == "admin" %>
              <li class="dropdown <%= 'active' if current_page?(users_path) %>">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="nav-header">Access</li>
                  <li><%= link_to "Users", users_path %></li>
                  <li class="divider"></li>
                  <li class="nav-header">Manage</li>
                  <li><%= link_to "Upload", uploads_path %></li>
                  <li><%= link_to "Import", import_reports_path %></li>
                </ul>
              </li>
            <%end %>
            <li class="<%= 'active' if current_page?(contacts_path) %>"><%= link_to "About", contacts_path %></li>
          </ul>
            <div class="nav pull-right">
              <%= link_to current_user.username, edit_user_registration_path, :class => "btn btn-warning" %>
              <%= link_to 'Logout', destroy_user_session_path, :method=>'delete', :class => "btn btn-inverse" %>
            </div>
          <% else %>
          </div>
          <div class="nav pull-right">
            <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => { :class =>"navbar-form pull-right" } ) do |f| %>
                <input class="span2" id="user_username" name="user[username]" type="text" placeholder="Username">
                <input class="span2" id="user_password" name="user[password]" type="password" placeholder="Password">
                <button type="submit" class="btn btn-warning">Sign in</button>
              <%= link_to 'Sign up', new_user_registration_path, :class => "btn btn-inverse" %>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">x</a>
      <%= msg  %>
    </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>